language: rust
rust:
  - stable
  - nightly

jobs:
  include:
    - stage: "Test"
      script: cargo test --verbose --all

    - stage: "Cli Test"
      script: /bin/sh ./tests.sh

    - stage: "Build"
      script: cargo build --release --verbose --all

    - stage: "Build without Features"
      script: cargo build --release --verbose --all --no-default-features
